import streamlit as st
import pandas as pd
import numpy as np
import os, sys
import matplotlib.pyplot as plt

# =========================================================
# PAGE CONFIG (MUST BE FIRST)
# =========================================================
st.set_page_config(page_title="Motorcycle Theft Intelligence", layout="wide")

# =========================================================
# PATH SETUP
# =========================================================
APP_DIR = os.path.dirname(__file__)
ROOT_DIR = os.path.abspath(os.path.join(APP_DIR, ".."))

if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

# =========================================================
# IMPORT ML MODULES
# =========================================================
from src.utils import load_model
from src.anomaly_detection import IsolationForestDetector

# =========================================================
# LOAD MODELS
# =========================================================
MODEL_PATH = os.path.join(ROOT_DIR, "models", "random_forest.pkl")
SCALER_PATH = os.path.join(ROOT_DIR, "models", "scaler.pkl")

model = load_model(MODEL_PATH)
scaler = load_model(SCALER_PATH)

# =========================================================
# SESSION STATE INIT
# =========================================================
if "last_prob" not in st.session_state:
    st.session_state["last_prob"] = 0.0

# =========================================================
# SIDEBAR NAVIGATION
# =========================================================
menu = st.sidebar.selectbox(
    "Navigation",
    ["Dashboard", "Risk Prediction", "Sensor Visualization", "Anomaly Detection"]
)

# =========================================================
# DASHBOARD
# =========================================================
if menu == "Dashboard":

    st.title("Motorcycle Theft Intelligence System")
    st.subheader("ML-Based Theft Detection & Sensor Monitoring")

    st.write(
        "This dashboard shows the most recent theft-risk assessment "
        "generated by the system."
    )

    # ---------- Read last risk from session ----------
    last_risk = st.session_state.get("last_prob", 0.0)
    last_risk = max(0.0, min(float(last_risk), 1.0))

    pct = int(last_risk * 100)
    bar = "■" * (pct // 5) + "□" * (20 - pct // 5)

    st.subheader("Current Threat Level")
    st.write(bar)
    st.write(f"Threat Level: {pct}%")

    if last_risk < 0.20:
        st.success("Normal riding behavior detected")
    elif last_risk < 0.40:
        st.warning("Minor disturbance detected")
    elif last_risk < 0.60:
        st.warning("Suspicious movement pattern")
    else:
        st.error("High likelihood of theft activity")

# =========================================================
# RISK PREDICTION
# =========================================================
elif menu == "Risk Prediction":

    st.title("Theft Risk Prediction")

    speed = st.slider("Speed Mean (km/h)", 0, 150, 55)
    speed_std = st.slider("Speed Std Dev", 0.0, 30.0, 5.0)
    accel = st.slider("Acceleration Mean (m/s²)", 0.0, 5.0, 0.8)
    accel_std = st.slider("Acceleration Std Dev", 0.0, 3.0, 0.3)
    vib = st.slider("Vibration Mean", 0.0, 3.0, 0.4)
    engine_ratio = st.slider("Engine ON Ratio", 0.0, 1.0, 0.9)
    gps_jump = st.slider("GPS Jump Mean", 0.0, 10.0, 0.2)

    row = pd.DataFrame([{
        "speed_mean": speed,
        "speed_std": speed_std,
        "accel_mean": accel,
        "accel_std": accel_std,
        "vib_mean": vib,
        "engine_ratio": engine_ratio,
        "gps_jump_mean": gps_jump
    }])

    FEATURES = [
        "speed_mean", "speed_std",
        "accel_mean", "accel_std",
        "vib_mean", "engine_ratio",
        "gps_jump_mean"
    ]

    row = row[FEATURES]
    row_scaled = scaler.transform(row)
    prob = float(model.predict_proba(row_scaled)[0][1])

    # ---------- SAVE TO SESSION ----------
    st.session_state["last_prob"] = prob

    st.write(f"### Theft Risk Score: **{prob:.3f}**")

    if prob > 0.60:
        st.error("HIGH THEFT PROBABILITY")
    elif prob > 0.35:
        st.warning("MODERATE RISK")
    else:
        st.success("LOW RISK")

# =========================================================
# SENSOR VISUALIZATION
# =========================================================
elif menu == "Sensor Visualization":

    st.title("Sensor Visualization")

    file = st.file_uploader("Upload Sensor CSV", type=["csv"])

    if file is not None:
        df = pd.read_csv(file)
        st.success("File uploaded successfully")
        st.dataframe(df.head())

        required = ["speed", "accel_x", "gyro_z", "vibration"]
        missing = [c for c in required if c not in df.columns]

        if missing:
            st.error(f"Missing columns: {missing}")
        else:
            for col, label in zip(
                required,
                ["Speed (km/h)", "Acceleration (m/s²)", "Gyro Z", "Vibration"]
            ):
                st.subheader(f"{label} Over Time")
                fig, ax = plt.subplots()
                ax.plot(df[col])
                ax.set_xlabel("Time Index")
                ax.set_ylabel(label)
                st.pyplot(fig)

    else:
        st.info("Upload a CSV file to visualize sensor data")

# =========================================================
# ANOMALY DETECTION
# =========================================================
elif menu == "Anomaly Detection":

    st.title("Sensor Anomaly Detection")

    file = st.file_uploader("Upload Sensor CSV", type=["csv"])

    if file is not None:
        df = pd.read_csv(file)
        st.dataframe(df.head())

        required = ["speed", "accel_x", "gyro_z", "vibration"]
        missing = [c for c in required if c not in df.columns]

        if missing:
            st.error(f"Missing columns: {missing}")
        else:
            X = df[required].fillna(0)

            detector = IsolationForestDetector(contamination=0.1)
            detector.fit(X)
            df["anomaly"] = detector.predict_labels(X)

            st.subheader("Anomaly Results")
            st.dataframe(df)

            st.subheader("Speed vs Acceleration (Anomaly Scatter)")
            fig, ax = plt.subplots()
            colors = df["anomaly"].map({-1: "blue", 1: "red"})
            ax.scatter(df["speed"], df["accel_x"], c=colors)
            ax.set_xlabel("Speed")
            ax.set_ylabel("Acceleration")
            st.pyplot(fig)

    else:
        st.info("Upload a CSV file to detect anomalies")
